app/routes.py
from flask import render_template, send_from_directory, Blueprint, current_app, redirect, url_for, session , request
import requests
import os
import mysql.connector
from dotenv import load_dotenv


routes_bp = Blueprint('routes', __name__)

@routes_bp.route('/')
def home():
    observer_lat = 12.97623
    observer_lng = 77.60329
    observer_alt = 900
    search_radius = 45
    category_id = 0
    api_key = "HZ3NA9-KEXVFH-A6FGN4-57O3"
    
    url = f"https://api.n2yo.com/rest/v1/satellite/above/{observer_lat}/{observer_lng}/{observer_alt}/{search_radius}/{category_id}&apiKey={api_key}"
    response = requests.get(url)
    data = response.json()  
    return render_template('index.html', satellites=data.get('above', []))

@routes_bp.route('/images/<filename>')
def get_image(filename):
    return send_from_directory(os.path.join(os.getcwd(), 'images'), filename)

@routes_bp.route('/about_us')
def about_us():
    return render_template('about_us.html')

@routes_bp.route('/potd')
def potd():
    return render_template('pic_of_the_day.html')

@routes_bp.route('/satellite-info/')
def satellite_info():
    try:
        with current_app.config['DB_CONNECTION'].cursor(dictionary=True) as cursor:

            cursor.execute('SELECT * FROM Satellite')
            satellites = cursor.fetchall()

            cursor.execute('SELECT * FROM Orbit_Details')
            orbit_details = cursor.fetchall()

            cursor.execute('SELECT * FROM Launch_Details')
            launch_details = cursor.fetchall()

            cursor.execute('SELECT * FROM Observer')
            observers = cursor.fetchall()

            cursor.execute('SELECT * FROM Obs_Coordinates')
            obs_coordinates = cursor.fetchall()

        satellites_with_details = []
        for satellite in satellites:
            satellite_observers = [observer for observer in observers if observer['Satellite_id'] == satellite['Satellite_id']]
            satellite_orbit = next((orbit for orbit in orbit_details if orbit['Satellite_id'] == satellite['Satellite_id']), None)
            satellite_launch_details = next((launch for launch in launch_details if launch['Launch_id'] == satellite['Launch_id']), None)

            satellite_coordinates = []
            for observer in satellite_observers:
                observer_id = observer['Observer_id']
                coordinates = next((coord for coord in obs_coordinates if coord['Observer_id'] == observer_id), None)
                if coordinates:
                    satellite_coordinates.append(coordinates)

            satellite['observers'] = satellite_observers
            satellite['orbit'] = satellite_orbit
            satellite['launch_details'] = satellite_launch_details
            satellite['coordinates'] = satellite_coordinates

            nord_id = satellite['nord_id']
            observer_lat = 12.97623 
            observer_lng = 77.60329  
            observer_alt = 900
            seconds = 1

            url = f"https://api.n2yo.com/rest/v1/satellite/positions/{nord_id}/{observer_lat}/{observer_lng}/{observer_alt}/{seconds}&apiKey=HZ3NA9-KEXVFH-A6FGN4-57O3"
            response = requests.get(url)
            data = response.json()

            if 'positions' in data:
                satellite['positions'] = data['positions']

            satellites_with_details.append(satellite)

        return render_template('satellite-info.html', launch_details=launch_details, satellites=satellites_with_details, obs_coordinates=obs_coordinates)
    
    except Exception as e:
        return f"An error occurred: {e}"
    

@routes_bp.route('/login/', methods=['GET', 'POST'])
def login():
    error = None
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        
        try:
            with current_app.config['DB_CONNECTION'].cursor(dictionary=True) as cursor:
                cursor.execute("SELECT * FROM users WHERE username = %s AND password_hash = %s", (username, password))
                user = cursor.fetchone()
                
                if user:
                    session['loggedin'] = True
                    session['id'] = user['id']
                    session['username'] = user['username']
                    return redirect(url_for('routes.sidebar'))
                else:
                    error = 'Invalid username or password'
        
        except mysql.connector.Error as err:
            error = f"An error occurred: {err}"
    
    return render_template('login.html', error=error)

@routes_bp.route('/signup/', methods=['GET', 'POST'])
def signup():
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        confirm_password = request.form['confirm_password']
        if password != confirm_password:
            return render_template('login.html', error='Password does not match the Confirm Password')
        try:
            with current_app.config['DB_CONNECTION'].cursor(dictionary=True) as cursor:
                cursor.execute("SELECT * FROM users WHERE username = %s", (username,))
                existing_user = cursor.fetchone()
                if existing_user:
                    return render_template('login.html', error='Username already exists')
                
            
                cursor.execute("INSERT INTO users (username, password_hash) VALUES (%s, %s)", (username, password))
                current_app.config['DB_CONNECTION'].commit()
                
            
                return redirect(url_for('routes.sidebar'))
        
        except mysql.connector.Error as err:
            return f"An error occurred: {err}"
    
    return render_template('login.html')

@routes_bp.route("/sidebar", methods=['GET'])
def sidebar():
    try:
        with current_app.config['DB_CONNECTION'].cursor(dictionary=True) as cursor:

            cursor.execute('SELECT * FROM Satellite')
            satellites = cursor.fetchall()

            cursor.execute('SELECT * FROM Orbit_Details')
            orbit_details = cursor.fetchall()

            cursor.execute('SELECT * FROM Launch_Details')
            launch_details = cursor.fetchall()

            cursor.execute('SELECT * FROM Observer')
            observers = cursor.fetchall()

            cursor.execute('SELECT * FROM Obs_Coordinates')
            obs_coordinates = cursor.fetchall()

        satellites_with_details = []
        for satellite in satellites:
            satellite_observers = [observer for observer in observers if observer['Satellite_id'] == satellite['Satellite_id']]
            satellite_orbit = next((orbit for orbit in orbit_details if orbit['Satellite_id'] == satellite['Satellite_id']), None)
            satellite_launch_details = next((launch for launch in launch_details if launch['Launch_id'] == satellite['Launch_id']), None)

            satellite_coordinates = []
            for observer in satellite_observers:
                observer_id = observer['Observer_id']
                coordinates = next((coord for coord in obs_coordinates if coord['Observer_id'] == observer_id), None)
                if coordinates:
                    satellite_coordinates.append(coordinates)
        

            satellite['observers'] = satellite_observers
            satellite['orbit'] = satellite_orbit
            satellite['launch_details'] = satellite_launch_details
            satellite['coordinates'] = satellite_coordinates
            satellites_with_details.append(satellite)

        return render_template('update-info.html', launch_details=launch_details, satellites=satellites_with_details, obs_coordinates=obs_coordinates)
    
    except Exception as e:
        return f"An error occurred: {e}"
    
@routes_bp.route('/add-launch-details/', methods=['POST'])
def add_launch_details():
    if request.method == 'POST':
        launch_id = request.form['Launch_id']
        operator_name = request.form['Operator_Name']
        launch_site = request.form['Launch_Site']
        launch_vehicle = request.form['Launch_Vehicle']
        launch_date = request.form['Launch_Date']
        country = request.form['Country']

        try:
            with current_app.config['DB_CONNECTION'].cursor() as cursor:
                cursor.execute("INSERT INTO Launch_Details (Launch_id, Operator_Name, Launch_Site, Launch_Vehicle, Launch_Date, Country) VALUES (%s, %s, %s, %s, %s, %s)",
                               (launch_id, operator_name, launch_site, launch_vehicle, launch_date, country))
                current_app.config['DB_CONNECTION'].commit()
                return render_template('update-info.html', message='Launch details added successfully')
        except mysql.connector.Error as err:
            current_app.logger.error(f"An error occurred: {err}")
            return render_template('update-info.html', error='Failed to add launch details')


@routes_bp.route('/add-satellite/', methods=['POST'])
def add_satellite():
    if request.method == 'POST':
        name = request.form['Name']
        launch_id = request.form['Launch_id']
        launch_date = request.form['Launch_Date']
        country_of_origin = request.form['Country_of_Origin']
        payload = request.form['Payload']
        type = request.form['Type']
        status = request.form['Status']

        try:
            with current_app.config['DB_CONNECTION'].cursor() as cursor:
                cursor.execute("INSERT INTO Satellite ( Name, Launch_id, Launch_Date, Country_of_Origin, Payload, Type, Status) VALUES (%s, %s, %s, %s, %s, %s, %s)",
                               (name, launch_id, launch_date, country_of_origin, payload, type, status))

app/templates/about_us.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <meta charset="UTF-8">
    <title>About Us</title>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/styles4.css') }}">
    
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary rounded" aria-label="Eleventh navbar example">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">
                <img src="/images/AStro.png" width="90" height="90" class="d-inline-block align-top" alt="logo" onclick="window.location.href='/'">   
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample09" aria-controls="navbarsExample09" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarsExample09">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link" onclick="window.location.href='/'">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" onclick="window.location.href='/satellite-info/'">Satellite Info</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" onclick="window.location.href='/potd'">Pitcure of the day</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" onclick="window.location.href='/login/'">Login</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="overlay"></div>
    <div class="container">
        <h1>About Us</h1>
        <a href="https://www.linkedin.com/in/-tejashegde/">
            <div class="profile">
                <img src="/images/tejas.jpg" alt="Image 1" class="circle-img" >
                <h2>Tejas Hegde</h2>
                <p>Information Science <br> RV Institute of Technology and Management</p>
            </div>
        </a>
        <a href="https://www.linkedin.com/in/vedashree-b-shetty-23668326a/">
            <div class="profile">
                <img src="/images/vedashree1.jpg" alt="Image 2" class="circle-img">
                <h2>Vedashree B</h2>
                <p>Information Science <br> RV Institute of Technology and Management</p>
            </div>
        </a>
    </div>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

app/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Orbitron:wght@400;700&family=Raleway:wght@400;700&display=swap">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login Page</title>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/login.css') }}">
</head>
<body>
    <div class="overlay"></div>
    <div class="wrapper">
        <div class="title-text">
          <div class="title login">Login Form</div>
          <div class="title signup">Signup Form</div>
        </div>
        <div id="loading-screen" class="loading-screen">
        <div class="form-container">
          <div class="slide-controls">
            <input type="radio" name="slide" id="login" checked>
            <input type="radio" name="slide" id="signup">
            <label for="login" class="slide login">Login</label>
            <label for="signup" class="slide signup">Signup</label>
            <div class="slider-tab"></div>
          </div>
          <div class="form-inner">
            <form action="{{ url_for('routes.login') }}" method="POST" class="login">
              {% if error %}
                <div class="error">{{ error }}</div>
              {% endif %}
              <div class="field">
                <input type="text" name="username" placeholder="Username" required>
              </div>
              <div class="field">
                <input type="password" name="password" placeholder="Password" required>
              </div>
              <div class="field btn">
                <div class="btn-layer"></div>
                <input type="submit" value="Login">
              </div>
              <div class="signup-link">Not a member? <a href="{{ url_for('routes.signup') }}">Signup now</a></div>
            </form>
            <form action="{{ url_for('routes.signup') }}" method="POST" class="signup">
              <div class="field">
                <input type="text" name="username" placeholder="Username" required>
              </div>
              <div class="field">
                <input type="password" name="password" placeholder="Password" required>
              </div>
              <div class="field">
                <input type="password" name="confirm_password" placeholder="Confirm password" required>
              </div>
              <div class="field btn">
                <div class="btn-layer"></div>
                <input type="submit" value="Signup">
              </div>
            </form>
          </div>
        </div>
      </div>
    <script src="{{ url_for('static', filename='js/login.js') }}"></script>
</body>
</html>

app/templates/update-info.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add Data</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Orbitron:wght@400;700&family=Raleway:wght@400;700&display=swap">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/styles3.css') }}">
</head>
<body>
    <!-- Navigation Bar -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">
            <img src="/images/AStro.png" width="90" height="90" class="d-inline-block align-top" alt="logo" onclick="window.location.href='/'">   
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" onclick="window.location.href='/'">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" onclick="window.location.href='/satellite-info/'">Satellite Info</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" onclick="window.location.href='/potd'">Pitcure of the day</a>
                </li>   
                <li class="nav-item">
                    <a class="nav-link" onclick="window.location.href='/about_us'">About us</a>
                </li>                
            </ul>
        </div>
    </nav>

    <div class="overlay"></div>

    <div class="flex-shrink-0 p-3" style="width: 300px;">
        <a href="#" class="d-flex align-items-center pb-3 mb-3 link-body-emphasis text-decoration-none border-bottom">
            <svg class="bi pe-none me-2" width="30" height="24"><use xlink:href="#bootstrap"/></svg>
            <span class="fs-5 ">Satellites List</span>
        </a>
        <ul class="list-unstyled">
            {% for satellite in satellites %}
            <li class="mb-1">
                <button class="btn btn-toggle d-inline-flex align-items-center rounded border-0 collapsed toggle-satellite" data-satellite-id="{{ satellite.Satellite_id }}">
                    -> {{ satellite.Name }}
                </button>
                <div class="collapse" id="satellite-{{ satellite.Satellite_id }}">
                    <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
                        <li><strong>Country of Origin:</strong> {{ satellite.Country_of_Origin }}</li>
                        <li><strong>Payload:</strong> {{ satellite.Payload }}</li>
                        <li><strong>Type:</strong> {{ satellite.Type }}</li>
                        <li><strong>Status:</strong> {{ satellite.Status }}</li>
                        <li><strong>Launch Operator:</strong> {% if satellite.launch_details %}{{ satellite.launch_details.Operator_Name }}{% else %}N/A{% endif %}</li>
                        <li><strong>Launch Date:</strong> {% if satellite.launch_details %}{{ satellite.launch_details.Launch_Date }}{% else %}N/A{% endif %}</li>
                        <li><strong>Launch Location:</strong> {% if satellite.launch_details %}{{ satellite.launch_details.Launch_Site }}{% else %}N/A{% endif %}</li>
                        <li><strong>Country:</strong> {% if satellite.launch_details %}{{ satellite.launch_details.Country }}{% else %}N/A{% endif %}</li>
                        <li><strong>Launch Vehicle:</strong> {% if satellite.launch_details %}{{ satellite.launch_details.Launch_Vehicle }}{% else %}N/A{% endif %}</li>
                        <li><strong>Semi-Major Axis:</strong> {% if satellite.orbit %}{{ satellite.orbit.Semi_Major_Axis }}{% else %}N/A{% endif %}</li>
                        <li><strong>Orbital Period:</strong> {% if satellite.orbit %}{{ satellite.orbit.Orbital_Period }}{% else %}N/A{% endif %}</li>
                        <li><strong>Apogee:</strong> {% if satellite.orbit %}{{ satellite.orbit.Apogee }}{% else %}N/A{% endif %}</li>
                        <li><strong>Inclination:</strong> {% if satellite.orbit %}{{ satellite.orbit.Inclination }}{% else %}N/A{% endif %}</li>
                        <li><strong>Perigee:</strong> {% if satellite.orbit %}{{ satellite.orbit.Prigee }}{% else %}N/A{% endif %}</li>
                        <li><strong>Eccentricity:</strong> {% if satellite.orbit %}{{ satellite.orbit.Eccentricity }}{% else %}N/A{% endif %}</li>
                        {% if satellite.observers %}
                            {% for observer in satellite.observers %}
                                <li><strong>Observer Name:</strong> {{ observer.Observer_Name }}</li>
                                <li><strong>Observer Location:</strong> {{ observer.Observer_Location }}</li>
                                <li><strong>Observation Date:</strong> {{ observer.Observation_Date }}</li>
                            {% endfor %}
                        {% else %}
                            <li>No Observer Details available</li>
                        {% endif %}
                        {% if satellite.coordinates %}
                            {% for coord in satellite.coordinates %}
                                <li><strong>Observer Latitude:</strong> {{ coord.Latitude }}</li>
                                <li><strong>Observer Longitude:</strong> {{ coord.Longitude }}</li>
                            {% endfor %}
                        {% else %}
                            <li>No Observer Coordinates available</li>
                        {% endif %}
                    </ul>
                </div>
            </li>
            {% endfor %}
        </ul>
    </div>  
    <section class="add" class="form-section" id="launch-details">
    <details>
    
            <summary>Add Launch Details</summary>
            <form action="{{ url_for('routes.add_launch_details') }}" method="POST" class="add-launch-details">
                <input type="text" name="Launch_id" placeholder="Launch ID" required>
                <input type="text" name="Operator_Name" placeholder="Operator Name" required>
                <input type="text" name="Launch_Site" placeholder="Launch Site" required>
                <input type="text" name="Launch_Vehicle" placeholder="Launch Vehicle" required>
                <input type="date" name="Launch_Date" placeholder="Launch Date" required>
                <input type="text" name="Country" placeholder="Country" required>
                <input type="submit" value="Add Launch Details">
            </form>
        </details>
    </section>  

    <section class="add" class="form-section" id="satellite">
        <details>
            <summary>Add Satellite</summary>
            <form action="{{ url_for('routes.add_satellite') }}" method="POST" class="add-satellite">
                <input type="text" name="Name" placeholder="Name" required>
                <input type="text" name="Launch_id" placeholder="Launch ID" required>
                <input type="date" name="Launch_Date" placeholder="Launch Date">
                <input type="text" name="Country_of_Origin" placeholder="Country of Origin">
                <input type="text" name="Payload" placeholder="Payload">
                <input type="text" name="Type" placeholder="Type">
                <input type="text" name="Status" placeholder="Status" required>
                <input type="submit" value="Add Satellite">
            </form>
        </details>
    </section>

    <section class="add" class="form-section" id="orbit-details">
        <details>
           <summary>Add Orbit Details</summary>
            <form action="{{ url_for('routes.add_orbit_details') }}" method="POST" class="add-orbit-details">
                <input type="text" name="Satellite_id" placeholder="Satellite ID" required>
                <input type="number" name="Semi_Major_Axis" placeholder="Semi Major Axis" required>
                <input type="number" name="Orbital_Period" placeholder="Orbital Period" required>
                <input type="number" name="Apogee" placeholder="Apogee" required>
                <input type="number" name="Inclination" placeholder="Inclination" required>
                <input type="number" name="Prigee" placeholder="Prigee" required>
                <input type="number" name="Eccentricity" placeholder="Eccentricity" required>
                <input type="submit" value="Add Orbit Details">
            </form>
        </details>
    </section>

    <section class="add" class="form-section" id="observer">
        <details>
            <summary>Delete Satellite</summary>
            <form action="{{ url_for('routes.add_observer') }}" method="POST" class="add-observer">
                <input type="text" name="Observer_id" placeholder="Satellite Name" required>
                <input type="submit" value="Delete Satellite">
            </form>
        </details>
    </section>

<section class="update" class="form-section" id="update-satellite">
    <details>
       <summary>Update Satellite</summary>
        <form action="{{ url_for('routes.update_satellite') }}" method="POST" class="update-satellite">
            <input type="text" name="satellite_name" placeholder="Satellite Name to Update" required>
            <!-- New Satellite Details -->
            <input type="text" name="name" placeholder="New Name">
            <input type="date" name="launch_date" placeholder="New Launch Date">
            <input type="text" name="country_of_origin" placeholder="New Country of Origin">
            <input type="text" name="payload" placeholder="New Payload">
            <input type="text" name="type" placeholder="New Type">
            <input type="text" name="status" placeholder="New Status">
            <!-- New Launch Details -->
            <input type="text" name="nord_id" placeholder="New Nord ID">
            <input type="text" name="operator_name" placeholder="New Operator Name">
            <input type="text" name="launch_site" placeholder="New Launch Site">
            <input type="text" name="launch_vehicle" placeholder="New Launch Vehicle">
            <input type="date" name="new_launch_date" placeholder="New Launch Date">
            <input type="text" name="new_launch_country" placeholder="New Launch Country">
            <!-- New Orbit Details -->
            <input type="number" name="new_semi_major_axis" placeholder="New Semi Major Axis">
            <input type="number" name="new_orbital_period" placeholder="New Orbital Period">
            <input type="number" name="new_apogee" placeholder="New Apogee">
            <input type="number" name="new_inclination" placeholder="New Inclination">
            <input type="number" name="new_prigee" placeholder="New Prigee">
            <input type="number" name="new_eccentricity" placeholder="New Eccentricity">
            <!-- New Observer Details -->
            <input type="text" name="observer_name" placeholder="New Observer Name">
            <input type="text" name="observer_location" placeholder="New Observer Location">
            <input type="date" name="observation_date" placeholder="New Observation Date">
            <input type="text" name="observer_country" placeholder="New Observer Country">
            <input type="text" name="observer_latitude" placeholder="New Observer Latitude">
            <input type="text" name="observer_longitude" placeholder="New Observer Longitude">
            <input type="submit" value="Update Satellite">
        </form>
    </details>
</section>
<section class="add" class="form-section" id="delete-satellite">
    <details>
        <summary>Delete Satellite</summary>
        <form action="{{ url_for('routes.delete_satellite', satellite_name=satellite_name) }}" method="POST" class="delete-satellite-form">
            <input type="text" name="satellite_name" placeholder="Enter Satellite Name" required>
            <input type="submit" value="Delete">
        </form>
    </details>
</section>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    <script>
        document.addEventListener('DOMContentLoaded', function () {
            const toggleButtons = document.querySelectorAll('.toggle-satellite');
            toggleButtons.forEach(button => {
                button.addEventListener('click', function () {
                    const satelliteId = this.getAttribute('data-satellite-id');
                    const satelliteDetails = document.getElementById(`satellite-${satelliteId}`);
                    satelliteDetails.classList.toggle('show');
                });
            });
        });
    </script>
</body>
</html>